# Generated by Django 4.0 on 2022-05-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('val', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('dp', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Datas',
                'db_table': 'test_data',
                'managed': True,
            },
        ),
    ]
